.travis.yml, buildout.cfg, src/ZODB/ConflictResolution.py, src/ZODB/Connection.py, src/ZODB/DB.py, src/ZODB/FileStorage/FileStorage.py
- Always use logger.exception rather than logging.error when logging
exceptions ar the error level.
- Fixed an incorrect call to logging.exceotion (like PR #26, but better :).
- Removed dependency pins and added one to overcome some breakage in
zope.testrunner.
None of this seems to be CHANGES worthy.
=> Cleaned up exception logging and changed pins

src/ZODB/FileStorage/FileStorage.py
This fix comes from the following ZEO log error:
```
2013-10-25 09:05:38,248 ERROR ZODB.ConflictResolution Unexpected error
Traceback (most recent call last):
File "ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/ConflictResolution.py", line 243, in tryToResolveConflict
oldData = self.loadSerial(oid, oldSerial)
File "ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/FileStorage/FileStorage.py", line 434, in loadSerial
raise POSKeyError(oid)
POSKeyError: 0x803e9f
```
This means that conflict resolution was started, but for some reason oldSerial does not exist in ZODB for given object. This object has a *lot* of old revisions, so although each revision is small a whole cluster was brought to a halt for 15 minutes, with disk loading data at 10MB/s (very probably limited by IOop/s), walking back this …
=> Stop looking for revision when past it.

.travis.yml, CHANGES.rst, setup.py, src/ZODB/_compat.py, tox.ini
As [discussed on the mailing list](https://groups.google.com/forum/#!topic/zodb/dRP-AGS7hmQ). Ref #36 and #37 
The only potential compatibility issue I'm aware of for Python 2.6 users is the [change in exceptions that are raised](https://github.com/zopefoundation/ZODB/issues/36#issuecomment-108438240). I wasn't sure if/where to mention that. 
Arguably this should be a bigger version bump than just 4.2.1 but I didn't change that either.
=> Make zodbpickle non-optional. 

.travis.yml, CHANGES.rst, setup.py, tox.ini
- (Both) Remove repetition of deps. Only install tests_require deps
explicitly. The previous comment in tox.ini about eggs in the
working directory doesn't apply, per @mgedmin.
- Setup Travis to use the local wheel cache for faster install times. I stole this from what I do in gevent, which works, but may not be optimal.
=> Cleanup tox.ini and .travis.yml as mentioned in #42 (and Python 3.5)

.gitignore, src/CHANGES.txt, src/ZODB/Connection.py, src/ZODB/tests/testMVCCMappingStorage.py
Nested connections try to clean up themselves multiple
times. This does not work.
I'd like to have a review from somebody, I don't feel 1000 % confident about the change.
=> Fixing uncaught exception problem on shutdown

.travis.yml, CHANGES.rst, setup.py, tox.ini
3.2 is no longer supported by our packaging / CI tools.
2.6 is long out-of-support from Python devs.
=> Drop support for Python 2.6 / 3.2.

src/ZODB/DB.py, src/ZODB/historical_connections.txt
Untested locally, copy-n-pasted from DemoStorage.test. Let's see what Travis says.
=> patch time.time in historical_connections to avoid windows failures.

CHANGES.rst, src/ZODB/FileStorage/FileStorage.py, src/ZODB/tests/testFileStorage.py
See the commit message for more information.
I wanted to attach the stress test I wrote to reproduce and understand the issue, but GitHub does not want *.py files. It was already sent to the mailing-list so you can find it there:
http://thread.gmane.org/gmane.comp.web.zope.zodb/12685/focus=12751
I'd like to also apply it on 3.10 branch.
/cc @vpelletier
=> Fix possible data corruption after FileStorage is truncated to roll back a transaction

src/ZODB/FileStorage/FileStorage.py
Changed to always empty the file pool.  I doubt that just flushing on
Python 2 was much of an optimization, and ... Python 2. :)
=> On Python 2 and Mac OS X, checkFlushAfterTruncate was failing.

CHANGES.rst, src/ZODB/ConflictResolution.py, src/ZODB/DemoStorage.py, src/ZODB/MappingStorage.py, src/ZODB/tests/HistoryStorage.py, src/ZODB/tests/testDemoStorage.py
Due to a bug in the Python implementation of TimeStamp, one of the added tests is disabled for PyPy.
I submitted zopefoundation/persistent#37, so if we do a new release of persistent quickly, we could wait to merge this one (with a bumped dependency in setup.py).
=> DemoStorage: add support for conflict resolution and fix history()

setup.py
=> Enforce minimium required Python versions: 2.7, 3.3.

CHANGES.rst, src/ZODB/FileStorage/FileStorage.py, src/ZODB/tests/TransactionalUndoStorage.py
Note that this is needed for a ZEO PR.
=> Fixed: FileStorage loadBefore didn't handle deleted/undone data correctly

src/ZODB/Connection.py, src/ZODB/DB.py, src/ZODB/ExportImport.py, src/ZODB/interfaces.py, src/ZODB/mvccadapter.py
This relatively small cleanup PR moves load to IMVCCStorage from IStorage.
It also loses the version argument from load and from IStorageWrapper.invalidate.
=> Move load to imvcc storage

src/ZODB/ActivityMonitor.py, src/ZODB/BaseStorage.py, src/ZODB/DB.py, src/ZODB/DemoStorage.py, src/ZODB/FileStorage/FileStorage.py, src/ZODB/FileStorage/fspack.py, src/ZODB/FileStorage/interfaces.py, src/ZODB/MappingStorage.py, src/ZODB/blob.py, src/ZODB/scripts/zodbload.py, src/ZODB/tests/MVCCMappingStorage.py, src/ZODB/tests/testDemoStorage.py, src/ZODB/tests/test_storage.py, src/ZODB/utils.py, src/ZODB/utils.txt
- Move from try/finally to with
- Start phasing out the _lock_acquire/_lock_release shortcuts
- Replace simpler @locked decorators with with statements.
I've come to prefer the with style tp the decorator style.
I think it's clearer.
(The decorators preceeded the Python with statement.)
I left the decorators in cases where they were used with preconditions.
This is mostly pretty mechanical, although it got a little delicate in
places and ... tests
=> Modernize and cleanup locking

src/ZODB/Connection.py, src/ZODB/DB.py, src/ZODB/interfaces.py, src/ZODB/multicommitadapter.py, src/ZODB/tests/TransactionalUndoStorage.py, src/ZODB/tests/blob_transaction.txt, src/ZODB/tests/testFileStorage.py
This makes sure that there is support for the new protocol by testing against a storage that supports the new protocol.
Note that ZEO has implemented undo asynchronously and ZODB has supported undone OIDs to be returned via ``tpc_vote`` for for some time. It could be argued whether this is a good thing or a bad thing. (My opinion is that it's simpler to return all affected oids in the vote result, but I don't feel strongly about it.)  It is, however, impractical to change this now.
=> Test that IMultiCommitStorages are supported

CHANGES.rst, src/ZODB/ConflictResolution.py, src/ZODB/Connection.py, src/ZODB/tests/testDemoStorage.py
To follow the interface.
That's the easy part, for the 4.x branch.
=> Only tpc_vote can report resolved conflicts with the new commit protocol

CHANGES.rst, src/ZODB/BaseStorage.py, src/ZODB/ConflictResolution.py, src/ZODB/Connection.py, src/ZODB/DemoStorage.py, src/ZODB/FileStorage/FileStorage.py, src/ZODB/FileStorage/tests.py, src/ZODB/MappingStorage.py, src/ZODB/tests/IExternalGC.test, src/ZODB/tests/StorageTestBase.py, src/ZODB/tests/blob_transaction.txt, src/ZODB/tests/testDemoStorage.py, src/ZODB/tests/testFileStorage.py
This does not clean up tests. In particular, the test using MultiCommitAdapter becomes useless (and IMO, MultiCommitAdapter too). Several changes from 74fba08ad4dc7311ca74c5c9da51c12e0e9dca86 could be also simplified.
=> Switch all storages to the new commit protocol

src/ZODB/tests/StorageTestBase.py
Fixes a bunch of test failures in RelStorage.
_dostore calls this with the results of `storage.store` (`None`) and `storage.tpc_vote` (set of oids---usually empty unless there's a resolved conflict, in which case you get a TypeError unpacking)
A similar thing will need to be done for the branch that is ZODB4, possibly just cherry-pick this commit?
=> Fix handle_all_serials for the new and old protocols.

src/ZODB/tests/BasicStorage.py, src/ZODB/tests/MTStorage.py, src/ZODB/tests/RevisionStorage.py, src/ZODB/tests/StorageTestBase.py
So try that. This slightly simplifies _dostore.
There are lots of other callers still so I didn't remove the functions entirely (but I could try if desired).
=> Per @jimfulton, handle_all_serials shouldn't be sniffing in ZODB5

CHANGES.rst, src/ZODB/ConflictResolution.py, src/ZODB/FileStorage/FileStorage.py, src/ZODB/tests/TransactionalUndoStorage.py
As part of a project to provide object-level commit locks for ZEO, I'm
refactiring FileStorage to maintain transaction-specific data in
Tranaction.data.  This involved undo.  In trying to figure this out, I
found:
- A bug in _undoDataInfo, which I verified with some tests and
- _transactionalUndoRecord was maddeningly difficult to reason about
(and thus change).
I was concerned less by the bug than my inability to know whether a
change to the code would be correct.
So I refactored the code, mainly transactionalUndoRecord, to make the
code easier to understand, fixing some logic errors (I'm pretty sure)
along the way.  This included lots of comments. (Comments are much
easier to compose when you're working out logic you didn't
understand.)
In addition to makeing the code cleaner, it allows …
=> Refactored FileStorage transactional undo

src/ZODB/tests/testCache.py
This test was spewing exceptions without failing for ZODB5.
The spew was an indication that something was wrong in this case. (The
test was broken.)
There had been some bug in the object cache that caused an infinite
loop when objects woke themselves up while being reaped.  This test is
a regression test for that bug.
The test was sloppy about transaction managers.  The test class
creates a bunch of connections using the threaded transaction manager,
but this test used a thread to execute the critical code.  As a
result, the synchronization methods weren't called.  This didn't
matter much with ZODB4.  The objects were still able to load their
state.
With ZODB5, the synchronization methods are important for proper MVCC
and because they weren't called, the objects' state couldn't be …
=> Fix testMinimizeTerminates

CHANGES.rst, src/ZODB/Connection.py, src/ZODB/interfaces.py, src/ZODB/mvccadapter.py, src/ZODB/tests/test_prefetch.py
Added a connection prefetch method that can be used to request  that a storage prefect data an application will need:
conn.prefetch(obj, ...)
Where arguments can be objects, object ids, or iterables of objects or object ids.
Added optional prefetch methods to the storage APIs. If a storage doesn't support prefetch, then the connection prefetch method is a noop.
=> Added a connection prefetch method

src/ZODB/Connection.py, src/ZODB/DB.py, src/ZODB/FileStorage/iterator.test, src/ZODB/tests/dbopen.txt, src/ZODB/tests/fix84.rst, src/ZODB/tests/synchronizers.txt, src/ZODB/tests/testCache.py, src/ZODB/tests/testConnection.py, src/ZODB/tests/testDB.py
This fixes #84.
Also:
- Added missing transaction ``begin`` call in the DB ``transaction()``
context manager.
- Added the ability to add a transaction note whan calling
``transaction()``.  This is useful (as would be the ability to pass
in other transaction meta data, but this was needed by (and this
tested) to make an existing test pass.
=> Changed DB root-object-initialization to use an open connection and more

CHANGES.rst, src/ZODB/fstools.py, src/ZODB/scripts/fstail.py, src/ZODB/scripts/tests/fstail.txt, src/ZODB/scripts/tests/test_doc.py
Before:
2016-07-01 09:41:50.416574: hash=d7101c5ee7b8e412d7b6d54873204421e09b7f34
user='' description='' length=1629 offset=58990284
After:
2016-07-01 09:41:50.416574: hash=d7101c5ee7b8e412d7b6d54873204421e09b7f34
user='' description='' length=1629 offset=58990261 (+23)
The structure of a FileStorage DB is such that it's easy to revert the last
transactions, by truncating the file at the right offset. With the above
change, `fstail` can now be used to get this offset.
In the above example:
truncate -s 58990261 Data.fs
would delete the transaction and all those after.
=> fstail: print the txn offset and header size, instead of only the data offset

src/ZODB/tests/TransactionalUndoStorage.py
=> checkTransactionalUndoIterator: do not expect iterator to return sorted oids

CHANGES.rst, src/ZODB/DemoStorage.py, src/ZODB/DemoStorage.test
Includes a (previously) failing test case.
Fixes #103.
=> Don't raise an AttributeError when DemoStorage successfully stores a blob first.

CHANGES.rst, src/ZODB/ConflictResolution.py, src/ZODB/tests/testconflictresolution.py
This fixes #97. See the docstring of the updated unit test for more explanation.
=> Call _p_resolveConflict() even if a conflicting change doesn't change the state

CHANGES.rst, doc/articles/old-guide/prog-zodb.rst, doc/guide/index.rst, doc/guide/install-and-run.rst, doc/guide/transactions-and-threading.rst, doc/reference/index.rst, doc/reference/transaction.rst, doc/reference/zodb.rst, src/ZODB/Connection.py, src/ZODB/tests/testdocumentation.py
This adds documentatuon on transactions and threading concerns.
There are some topics, like application design and conflict resolution
that might want a deeper treatment, but would probably be better
handled through articles or dedicated topics. (I want to avoid
individual topics being too long or weedy to read, where practical.)
Writing this, I stumbled a bit over thread-local transaction managers.
For most applications, they don't add anything over accessing
transaction managers on connections and actually provide an
opportunity to fail. I'm convinced that it should be possible to do
most transaction management through connections and that the API
provided by transaction managers and the transaction package should be
reserved for distributed transactions.
I didn't mention gevent. I thik …
=> Documentation on transactions and threading.

.coveragerc, .gitignore, .travis.yml, buildout.cfg
Set this up on travis.
This was just slightly tricky because of the use of 'j99' in the call to bin/test.
=> Enable using coverage and coveralls for coverage reporting.

src/ZODB/FileStorage/format.py, src/ZODB/POSException.py, src/ZODB/_compat.py, src/ZODB/blob.py, src/ZODB/tests/IteratorStorage.py, src/ZODB/tests/testCache.py, src/ZODB/tests/testDB.py, src/ZODB/tests/testPersistentList.py, src/ZODB/tests/testPersistentMapping.py, src/ZODB/tests/util.py, src/ZODB/utils.py
To help coverage numbers.
- Remove version tests for < 2.6. This removes some code and dedents/clarifies some other. (2.6 is unsupported. 2.5 is even longer unsupported). (The `w=0`  URL query argument can help make the diff cleaner in the dedent case.)
- Consistently spell remaining version checks as PY2 or PY3 for ease of finding them.
- Remove utils.deprecated3[78]. These haven't been used in a long time.
=> Remove obsolete code

doc/guide/index.rst, doc/guide/install-and-run.rst, doc/guide/transactions-and-threading.rst, doc/guide/writing-persistent-objects.rst, doc/tutorial.rst
I was looking through the very helpful ZODB documentation and found a few typos. Hopefully I understood the intent of the affected sentences correctly, and did not simply introduce new typos.
=> Fix a few typos in documentation

doc/guide/transactions-and-threading.rst, src/ZODB/tests/BasicStorage.py
- Use assertEqual rather than assertTrue for better error messages.
- Fixed a typo that caused an assertion to be missed.
=> Cleaned up check_checkCurrentSerialInTransaction

CHANGES.rst, src/ZODB/BaseStorage.py, src/ZODB/Connection.py, src/ZODB/interfaces.py, src/ZODB/tests/test_TransactionMetaData.py
storage that some storages rely on.
=> Fixed: ZODB.Connection.TransactionMetaData didn't custom data

.coveragerc, CHANGES.rst, src/ZODB/Connection.py, src/ZODB/DB.py
=> Connection.new_oid delegates to its storage, not the DB.

CHANGES.rst, src/ZODB/Connection.py
Doing so leads to race conditions.
In particular, there can be an AttributeError. This was introduced in 5.0.1.
See https://github.com/zodb/zodbshootout/issues/26 for details.
=> Don't manipulate Connection state after it has been returned to the pool.

CHANGES.rst, src/ZODB/DB.py, src/ZODB/tests/testDB.py
This backports a change from commit 227953b977a9e195c4ce9bbb9acd9c5ee60c333a.
NEO, as well as ZEO+server_sync (ERP5 backports this feature with a monkey-patch), pings the server (primary master node in the case of NEO) on new transactions. However, this round-trip is actually performed by the thread that also does tasks requiring to lock the DB, like processing of invalidations.
Since transaction 1.6.1 (more precisely zopefoundation/transaction@e581a120a612d54eea9240606a5723ff73952eb0), IStorage.sync() is called indirectly by DB.open() when a transaction has already begun, and the DB must not be locked when this happens.
=> Fix deadlock with storages that "sync" on a new transaction

CHANGES.rst, src/ZODB/Connection.py, src/ZODB/interfaces.py, src/ZODB/tests/testConnection.py
See: https://github.com/zodb/relstorage/issues/147
- Call new afterCompletion API on storages to allow them to free
resources after transaction complete.  See:
https://github.com/zodb/relstorage/issues/147
- Take advantage of the new transaction-manager explicit mode to avoid
starting transactions unnecessarily when transactions end.
This differs from the previous PR:
- No longer implement seatbelts, as the transaction package does that.
- No longer configure explicit mode via DB.  We get explicit mode from the transaction manager.
=> Notify storages that transactions have completed.

.travis.yml, src/ZODB/tests/TransactionalUndoStorage.py
This fixes leaking connections (relying on the GC to close them).
Tested with RelStorage.
Fixes #138 
Addition of try/finally blocks only. May be easier to view with ?w=0
=> TransactionUndoStorage tests close the conn and db

src/ZODB/FileStorage/FileStorage.py, src/ZODB/tests/testConfig.py, src/ZODB/tests/testFileStorage.py
... instead of silently creating empty database on such opens.
Use-case for this are utilities like e.g. zodbdump and zodbcmp which
expect such storage opens to fail so that the tool can know there is no
such storage and report it to user.
In contrast current state is: read-only opens get created-on-the-fly
empty storage with no content, but which can be iterated over without
getting any error.
This way e.g. `zodbdump non-existent.fs` produces empty output _and_
exit code 0 which is not what caller expects.
=> FileStorage: Report problem on read-only open of non-existent file

doc/articles/multi-zodb-gc.rst
RelStorage 2.0 can and should use zc.zodbdgc for reference collecting and packing in a multi-db, so long as its history free.
=> Update RelStorage information in multi-zodb-gc document

CHANGES.rst, DEVELOPERS.rst, README.rst, setup.py
I noticed the other day that the PyPI page for the current release is hosed WRT ReST:
https://pypi.python.org/pypi/ZODB/5.2.0
In fixing this, I realized that a lot of text was out of date and not well suited to a PyPI page, so I:
- Split developer info into a separate doc.
- Simplified the README and setup script.
=> Fix PyPI page

CHANGES.rst, src/ZODB/Connection.py, src/ZODB/FileStorage/FileStorage.py, src/ZODB/blob.py, src/ZODB/tests/testblob.py
This basically makes blob permissions come (more or less) from whatever the user has set for new directories.
This fixes: #155 .
It replaces: #1 .
I predict windows headaches, but maybe not. We need to get appveyor working to find out. That will be a separate PR.
=> Blob default permissions

CHANGES.rst, src/ZODB/blob.py
Fixes #158.
Those methods aren't tested by ZODB, apparently (but they are by RelStorage).
=> Import warnings on demand.

CHANGES.rst, src/ZODB/blob.py
Profiling (https://github.com/zodb/zodbshootout/pull/32/) showed that
this method was the only blob-related method that showed up in a test
of creating blobs, other than those that actually performed IO.
With this change its total and cumulative time drops from 0.003/0.004
to 0.001/0.002 in a small benchmark. Blobs created per second shows a
small but consistent improvement.
Before:
```
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
100    0.005    0.000    0.005    0.000 {built-in method rename}
100    0.004    0.000    0.004    0.000 {function BlobFile.close at 0x1080d3a60}
200    0.003    0.000    0.004    0.000 blob.py:576(oid_to_path)
101    0.003    0.000    0.003    0.000 {built-in method mkdir}
100    0.002    0.000    0.002    0.000 blob.py:333(__init__)
402 …
```
=> Speed up ZODB.blob.BushyLayout.oid_to_path on Python 3

src/ZODB/blob.py
Avoid waiting for GC to close file. Could explain some bug with RelStorage
=> Backport from 4.0 and later

.travis.yml, CHANGES.rst, README.rst, doc/index.rst, setup.cfg, setup.py, src/ZODB/tests/testdocumentation.py, tox.ini
- Fix running tests using tox.
- Whitespace cleanup in setup.py (spaces around operators and continuing indentation).
- Fix running tests on PyPy on Travis. (They were just being skipped.)
- Use latest PyPy versions on Travis.
- Add python_requires to setup metadata.
- Drop classifier and tests for Python 3.3 (though PyPy3 on Travis is still 3.3 so it is still technically being tested). This fixes #148.
=> Add support for 3.6, drop 3.3

CHANGES.rst, src/ZODB/mvccadapter.py, src/ZODB/tests/test_mvccadapter.py
Fixes #78.
Also adjust the base wrapper's __getattr__ to be faster (500 vs 711ns in a benchmark of the common case) and behave the same on Python 2 vs Python 3 with regards to exceptions, should a method be implemented as an descriptor. In practice this probably makes no difference whatsoever, it's just the same pattern used for forwarding release.
=> HistoricalStorageAdapter forwards release() to its instance

CHANGES.rst, src/ZODB/_compat.py, src/ZODB/blob.py
Previously protocol 1 was used. The higher protocol is more efficient for new-style classes (all persistent objects are new-style), according to the docs, at the cost of being very slightly less space efficient for old-style classes.
In tests of a persistent object with two trivial numeric attributes, the higher protocol was 12 bytes smaller, and serialized and deserialized 1us faster. Introducing a reference to another new-style
class (with a small dict and list of strings for attributes) for a more realistic test made the higher protocol twice as fast to serialize (20.5 vs 10.3us), almost half the size (215 vs 142 bytes), and it deserialized 30% faster (6.5 vs 4.6us).
On Python 2, this will now allow open ``file`` objects to be pickled (loading the object will result in a closed file); …
=> Use a higher pickle protocol for serializing objects on Python 2

.travis.yml, setup.py
Unpin specific PyPy versions, blacklist 3.3 in `setup.py` as Travis now offers a new enough PyPy 3.
=> Unpin specific PyPy versions, blacklist 3.3 in `setup.py`

src/ZODB/Connection.py, src/ZODB/DB.py
Some parts of the code to close Connection/DB and release resources looks too complicated for me. At least, there is questionable behaviour and also some possible micro optimization. Above all, I've started to look at this for some other change that would depend on it.
=> Review Connection/DB closure

CHANGES.rst, src/ZODB/FileStorage/fspack.py
@hvelarde had an issue with a db that couldn't be packed due to an object that could not be found. This makes sure that the entire oid is reported in that case, instead of just the final 2 bytes.
Or would it be better to handle this in `fsIndex`'s `__getitem__`?
=> Report full oid of missing object during pack

src/ZODB/ExportImport.py, src/ZODB/utils.py
I'm working on a project where I need to copy object trees that contain many (10s of thousands) of large blobs.  The easiest way to do this (for my application so far) is to leverage export/import.  I wanted to avoid extra file I/O, so I tried exporting to and importing from a pipe.  This failed because import looks for blob markers and then seeks back when they're not found, which is most of the time.  The blob marker (and associated seek) wasn't necessary because the blob object record can serve as a marker.
The primary change in this PR is to leverage blob object records as blob data markers, thus avoiding seeks and permitting pipes to be used.  For backward compatibility, blob-data markers are still written on output and read and checked on input.
In addition to allowing pipes to be …
=> Avoid seeking on import

src/ZODB/broken.py
I have seen a little typo in doctest comments and I fixed it. King regards.
=> Fix typo in doctest documentation of find_global method

CHANGES.rst, src/ZODB/_compat.py, src/ZODB/serialize.py, src/ZODB/tests/testSerialize.py
=> Save object ids as zodbpickle.binary and use pickle protocol 3 for Python 2

src/ZODB/MappingStorage.py, src/ZODB/tests/testMappingStorage.py
This never would have worked, there's an obvious typo, and it bit me today when trying to persist a stack of DemoStorages in a test run, for debugging.
=> Fix infinite recursion when copying from a MappingStorage to a FileStorage

CHANGES.rst, setup.py
This is required to avoid a memory leak on Python 2.7.
See #203.
=> Bump dependency on zodbpickle to at least 1.0.1

CHANGES.rst, setup.py, tox.ini
Skipping CI because tests will fail until #217 is merged.
Fixes #218.
=> Remove support for 'python setup.py test'. [skip ci]

.travis.yml, CHANGES.rst, appveyor.yml, setup.py, src/ZODB/Connection.py, src/ZODB/scripts/tests/test_doc.py, src/ZODB/tests/testConnection.py, src/ZODB/tests/test_TransactionMetaData.py, tox.ini
And fix all the deprecations it reports.
Fixes #214 and fixes #215 (well there's one remaining deprecation in 'manuel')
Based on #217 so that all tests pass.
=> Add Python 3.7 support. 

CHANGES.rst, src/ZODB/tests/testUtils.py, src/ZODB/utils.py
=> p64 and p64 are faster and create more informative exceptions.

.travis.yml, CHANGES.rst, appveyor.yml, setup.py, src/ZODB/scripts/tests/test_repozo.py, src/ZODB/tests/PackableStorage.py, src/ZODB/tests/RecoveryStorage.py, src/ZODB/tests/RevisionStorage.py, src/ZODB/tests/testCache.py, src/ZODB/tests/testblob.py, src/ZODB/tests/util.py, tox.ini
This also makes us more deterministic. (Based on [code I wrote for nti.testing](https://github.com/NextThought/nti.testing/blob/master/src/nti/testing/time.py).)
On my machine, this speeds up a sequential test run from 4:08 to 1:30. An AppVeyor 2.7, where we run tests sequentially, the time went from over five minutes to 2:35.
We no longer get much benefit from running the layer tests in parallel on CI, in fact it looks like the overhead actually slows them down slightly, so stop doing that.
This obsoletes the hack we have for running coverage in parallel on CI; I plan a followup PR to remove that (if this is accepted). 
The tests fail on appveyor 3.4 because its version of setuptools is so old. I would like to also address that in the same PR that adjusts the coverage hacks on Travis. …
=> Avoid most calls to time.sleep() in the tests by mocking time.[gm]time

CHANGES.rst, src/ZODB/scripts/repozo.py, src/ZODB/scripts/tests/test_repozo.py
This PR aims to reduce the number of IO operations when recovering a ZODB backup with repozo, when user wants to also verify the data. The idea is to add a new option for the -R/--recovery mode which will run the same checks as the -v/--Verify mode, but by reading data in increment files only once.
Also, I did a first commit to prevent the concat() function to close the file descriptor, as currently it is closed twice : once in concat(), and once in the function calling concat(). I think it should be the responsability of the one opening the file to also close it. What surprised me is that there was an assertion in tests checking that concat() was indeed closing the file descriptor. I couldn't find in the git history the explanation why.
=> Repozo : add an option to verify on recovery

CHANGES.rst, src/ZODB/DB.py, src/ZODB/tests/testDB.py
Fixes #268.
Additionally, it no longer eagerly opens the new instance, waiting until it actually needs it, and disposes of it (not just closes it) when it is done, thus breaking the reference cycle outlined in #268.
I did the closing in both `tpc_finish` and `tpc_abort` because one or the other of those (logically) *must* be called once `tpc_begin` was called. In the implementation of `transaction`, it looks like the plain `abort()` method is also always called, but the docs don't make it clear that that's required (in fact, they say that `abort` "may also be called").
=> TransactionalUndo closes storages it opens.

CHANGES.rst, src/ZODB/BaseStorage.py, src/ZODB/Connection.py, src/ZODB/FileStorage/FileStorage.py, src/ZODB/fsrecover.py, src/ZODB/interfaces.py, src/ZODB/tests/IteratorStorage.py, src/ZODB/tests/StorageTestBase.py, src/ZODB/tests/testFileStorage.py, src/ZODB/tests/test_TransactionMetaData.py
IStorage implementations used to do this task themselves which leads to code
duplication and sometimes bugs (one was fixed recently in NEO). Like for object
serialization, this should be done by the upper layer (Connection).
This commit also provides a way to get raw extensions data while iterating
over transactions (this is actually the original purpose[2]). So far, extension
data could only be retrieved unpickled, which caused several problems:
- tools like `zodb dump` [1] cannot dump data exactly as stored on a
storage. This makes database potentially not bit-to-bit identical to
its original after restoring from such dump.
- `zodb dump` output could be changing from run to run on the same
database. This comes from the fact that e.g. python dictionaries are
unordered and so when …
=> Make TransactionMetaData in charge of (de)serializing extension data

CHANGES.rst, src/ZODB/Connection.py
This is more consistent with its ``__len__`` (thanks @jmuchemb for pointing that out) and provides a better figure for existing logging. It's still approximate, but less wildly wrong than before.
Fixes #282
=> Make TmpStore implement its own getSize

src/ZODB/interfaces.py, src/ZODB/scripts/migrate.py, src/ZODB/tests/BasicStorage.py, src/ZODB/tests/IteratorStorage.py, src/ZODB/tests/RevisionStorage.py, src/ZODB/tests/StorageTestBase.py, src/ZODB/tests/TransactionalUndoStorage.py
In a few cases, they were passing native strings, which complicates things on Python 3.
This is consistent with what persistent.Persistent and Connection actually do.
RelStorage previously had a special case just for these tests.
=> Tests: Always pass bytes for the previous serial param of storage.store

appveyor.yml
Fixes issues with zc.buildout and version pins (https://github.com/zopefoundation/ZODB/pull/295#issuecomment-593805066)
(Hopefully. Still waiting for the CI to run.)
=> Simplify appveyor.yml.

HISTORY.rst, README.rst, doc/articles/ZODB-overview.rst, doc/articles/multi-zodb-gc.rst, doc/guide/install-and-run.rst, doc/guide/transactions-and-threading.rst, doc/guide/writing-persistent-objects.rst, doc/index.rst, doc/reference/storages.rst, src/ZODB/DemoStorage.py
This PR updates the package URLs to the pypi.org domain and normalizes used protocol to HTTPS.
=> Update package links from pypi.python.org to pypi.org

src/ZODB/FileStorage/FileStorage.py, src/ZODB/tests/testFileStorage.py
ZODB tries to avoid saving empty transactions to storage on
`transaction.commit()`. The way it works is: if no objects were changed
during ongoing transaction, ZODB.Connection does not join current
TransactionManager, and transaction.commit() performs two-phase commit
protocol only on joined DataManagers. In other words if no objects were
changed, no tpc_*() methods are called at all on ZODB.Connection at
transaction.commit() time.
This way application servers like Zope/ZServer/ERP5/... can have
something as
try:
transaction.commit()    # processed ok
except:
transaction.abort()
in top-level code to process requests without creating many on-disk
transactions with empty data changes just because read-only requests
were served.
Everything is working as intended.
However at storage level, …
=> FileStorage: Save committed transaction to disk even if changed data is empty

src/ZODB/FileStorage/FileStorage.py, src/ZODB/tests/testFileStorage.py
[ This is ZODB4 backport of commit bb9bf539
(https://github.com/zopefoundation/ZODB/pull/298) ]
ZODB tries to avoid saving empty transactions to storage on
`transaction.commit()`. The way it works is: if no objects were changed
during ongoing transaction, ZODB.Connection does not join current
TransactionManager, and transaction.commit() performs two-phase commit
protocol only on joined DataManagers. In other words if no objects were
changed, no tpc_*() methods are called at all on ZODB.Connection at
transaction.commit() time.
This way application servers like Zope/ZServer/ERP5/... can have
something as
try:
transaction.commit()    # processed ok
except:
transaction.abort()
in top-level code to process requests without creating many on-disk
transactions with empty data changes just because …
=> [ZODB4] FileStorage: Save committed transaction to disk even if changed data is empty (backport)

CHANGES.rst, src/ZODB/FileStorage/tests.py, src/ZODB/interfaces.py, src/ZODB/mvccadapter.py, src/ZODB/tests/testConnection.py, src/ZODB/tests/testmvcc.py
Since commit b5895a5c23309ff2dfe8fd853b838a0c5e349210, a ZEO test fails as follows:
File "src/ZEO/tests/drop_cache_rather_than_verify.txt", line 114, in drop_cache_rather_than_verify.txt
Failed example:
conn.root()[1].x
Expected:
6
Got:
1
Earlier in the test, the ZEO server is restarted and then another client commits. When disconnected, the first client does not receive invalidations anymore and the connection gets stuck in the past until there's a new commit after it reconnected. It was possible to make the test pass with the following patch:
```diff
--- a/src/ZEO/ClientStorage.py
+++ b/src/ZEO/ClientStorage.py
@@ -357,6 +357,7 @@ def notify_connected(self, conn, info):
if self._db is not None:
+            self._db.invalidate(self.lastTransaction(), ())
self._db.invalidateCache() …
```
=> mvccadapter: check if the last TID changed without invalidation

CHANGES.rst
`ConnectionPool` and `ConnectionPool.map` both had docstrings and were used by third-party code. #280 removed that method but didn't leave a note. People should be warned about this potentially breaking change or they might find 5.6.0 to be surprising.
Even if the better thing to do is to restore `map()` in 5.6.1, I think 5.6.0 still needs a note. It's an easy thing to fix, at least in the cases I've seen that broke so I'm not too worried about it, as long as there's a heads-up.
=> Add a change note for #280

src/ZODB/tests/BasicStorage.py
It is pointless for lastTransaction() to block until it is allowed the
TID of a transaction that has just been committed, because it may still
not be the real last TID (e.g. for some storage implementations,
invalidations are received from a shared server via the network).
While invalidations are still being processed, it's fine to return
immediately with the previous last TID.
This was clarified in commit 4a6b0283f61427c7a2d8086a271bcdfb1cb53593
("mvccadapter: check if the last TID changed without invalidation").
=> Relax assertion in check_tid_ordering_w_commit test

buildout.cfg
Fix errors in test on python2.7 and pypy:
from sphinxcontrib.serializinghtml.jsonimpl import dumps as dump_json
File "/home/travis/build/zopefoundation/ZODB/eggs/sphinxcontrib_serializinghtml-1.1.4-py2.7.egg/sphinxcontrib/serializinghtml/__init__.py", line 177
def setup(app: Sphinx) -> Dict[str, Any]:
^
SyntaxError: invalid syntax
=> Fix requirements for sphinx on python2

.travis.yml
setutools 50.0.0 does not seem compatible with the pypy3 used on travis.
=> .travis.yml: pin setuptools to 49.6 on pypy3

doc/tutorial.rst
To manually mark an object modified, `_p_changed` attribute must be set, no `_p_changed__`
=> doc: fix typo _p_changed

CHANGES.rst, src/ZODB/scripts/fsrefs.py
Access objects in the order of their position in file instead of in the order
of their OID. This should give dramatical speedup when data are on HDD.
For example @perrinjerome reports that on a 73Go database it takes
almost 8h to run fsrefs (where on the same database, fstest takes 15
minutes) [1,2]. After the patch fsrefs took ~80 minutes to run on the same
database. In other words this is ~ 6x improvement.
Fsrefs has no tests. I tested it only lightly via generating a bit
corrupt database with deleted referred object(*), and it gives the same
output as unmodified fsrefs.
oid 0x0 __main__.Object
last updated: 1979-01-03 21:00:42.900001, tid=0x285cbacb70a3db3
refers to invalid objects:
oid 0x07 missing: '<unknown>'
oid 0x07 object creation was undone: '<unknown>'
This "take 2" version is …
=> fsrefs: Optimize IO  (take 2)

CHANGES.rst, doc/requirements.txt
According to dependabot Pygment versions < 2.7.4 are vulnerable.
I already switched https://readthedocs.org/projects/zodb-docs/ to Python 3.x.
=> Security fix documentation dependencies

src/ZODB/tests/BasicStorage.py, src/ZODB/tests/MVCCMappingStorage.py, src/ZODB/tests/util.py
Add test that exercises open vs invalidation race condition that, if
happen, leads to data corruption. We are seeing such race happening on
storage level in ZEO (https://github.com/zopefoundation/ZEO/issues/166),
and previously we've seen it also to happen on Connection level
(https://github.com/zopefoundation/ZODB/issues/290). By adding this test
to be exercised wrt all storages we make sure that all storages stay
free from this race.
And it payed out. Besides catching original problems from
https://github.com/zopefoundation/ZODB/issues/290 and
https://github.com/zopefoundation/ZEO/issues/166 , this test also
discovered a concurrency bug in MVCCMappingStorage:
Failure in test check_race_open_vs_invalidate (ZODB.tests.testMVCCMappingStorage.MVCCMappingStorageTests)
Traceback (most recent …
=> tests: Add test for open vs invalidation race

docs/articles/ZODB2.rst, src/ZODB/Connection.py, src/ZODB/FileStorage/fsdump.py, src/ZODB/cross-database-references.rst, src/ZODB/tests/testblob.py
There are small typos in:
- docs/articles/ZODB2.rst
- src/ZODB/Connection.py
- src/ZODB/FileStorage/fsdump.py
- src/ZODB/cross-database-references.rst
- src/ZODB/tests/testblob.py
Fixes:
- Should read `committed` rather than `commited`.
- Should read `resetting` rather than `reseting`.
- Should read `debugging` rather than `debuggin`.
- Should read `constructor` rather than `contructor`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

.meta.toml, src/ZODB/tests/BasicStorage.py, src/ZODB/tests/racetest.py, src/ZODB/tests/util.py, src/ZODB/utils.py, tox.ini
Add test for Bug2 described in https://github.com/zopefoundation/ZEO/issues/209 + modernize race testing infrastructure. We add this test here, so that it can be run automatically for all storages - e.g. both ZEO and NEO.
ZEO currently can corrupt data if client disconnects simultaneously to another client performing `tpc_finish`. It fails e.g. as follows:
```console
(z-dev) kirr@deca:~/src/wendelin/z/ZEO5$ ZEO_MTACCEPTOR=1 zope-testrunner -fvvvx --test-path=src -t check_race_external_invalidate_vs_disconnect
/home/kirr/src/wendelin/venv/z-dev/bin/zope-testrunner traceio=True
/home/kirr/src/wendelin/z/ZEO5/src/ZEO/StorageServer.py:51: DeprecationWarning: The mtacceptor module is deprecated and will be removed in ZEO version 6.
'in ZEO version 6.', DeprecationWarning)
Running tests at …
```
=> Modernize race tests and add test that catches ZEO corruption on invalidation / disconnect 

CHANGES.rst, src/ZODB/scripts/zodbload.py, src/ZODB/tests/racetest.py
This PR fixes problems with the `racetest`s observed during work on "https://github.com/zopefoundation/ZEO/pull/225".
It uses daemon (rather than normal) threads to avoid deadlock on shutdown when one of the test threads has not finished. It treats the failure for a test thread to finish as a test failure.
=> Fix `racetest` problems

CHANGES.rst, src/ZODB/scripts/repozo.py
The argument `--with-verification` for `--recover` does not work.
"verify" is used 39 times in the script, and "verification" is used only 2 times.
I think the two occurrences of `--with-verification` should be `--with-verify`. 
The script then works and the doc is correct.
=> fix(repozo) `--with-verify` argument

docs/tutorial.rst
The newt db project appears to be dead; the domain name now leads to a domain parking website.
=> Remove references to newt db

CHANGES.rst, src/ZODB/scripts/repozo.py, src/ZODB/scripts/tests/test_repozo.py
When verification failed, repozo prints a message on standard error, but the program always exits with a return code indicating a success. In case of error it's more natural to exit with an error return code.
=> repozo: exit with non-zero code in case of verification failure

CHANGES.rst, src/ZODB/FileStorage/FileStorage.py, src/ZODB/tests/RecoveryStorage.py, src/ZODB/tests/testFileStorage.py
The case of a history like this:
- T0 initialize an object in state 0
- T1 modifies object to state 1
- T2 modifies object to state 2
- T3 undo T2 and T1, bringing back to state 0
- T4 modified object to state 3
- T5 undo T4, bringing back object to state 0
was not correct after `restore`: the state is 1 instead of the expected 0.
This is because T3 contains two data records:
- an undo of T2, with a backpointer to the data of state 1
- an undo of T1, with a backpointer to the data of state 0
When restoring T5 (the undo of T4), the transaction is made of one data record, with a backpointer that is copied from the backpointer from T3, but this uses backpointer from the first record for this object, which is incorrect, in such a case where there is more than one backpointer for the same oid, …
=> FileStorage: fix rare data corruption when using restore after multiple undos

CHANGES.rst, src/ZODB/scripts/repozo.py, src/ZODB/scripts/tests/test_repozo.py
When running backup or verify, "--with-verify option is ignored" warning was issued even when this option was not passed
=> repozo: prevent an incorrect "option ignored" warning

CHANGES.rst, src/ZODB/scripts/repozo.py
This was working on python2, but on python3,
```
repozo -v --recover --repository backups/ > restored.fs
```
failed with
```  
TypeError: write() argument must be str, not bytes
```
=> repozo: fix recover on stdout

CHANGES.rst, src/ZODB/FileStorage/FileStorage.py, src/ZODB/tests/testFileStorage.py
In commit 8160568b (FileStorage: fix rare data corruption when using
restore after multiple undos (#395)) we fixed FileStorage.restore to
work correctly in the presence of multiple undos for the same oid in the 
same transaction by reworking oid data records of one transaction to be
all scanned in the loop. But unfortunately that commit introduced a
regression:
When restore is instructed to do an undo, in other words, to make a copy
of oid data by referring to that data by backpointer, it checks content
of the pointed-to record, and if data content there does not match data
content passed to restore call, the copy-via-backpointer optimization is
silently disabled. However 8160568b contained a thinko when doing the 
check: after discovering pointed-to oid data record, the intent there it …
=> FileStorage: Fix restore to correctly check restored data content
