zopefoundation/ZODB

CHANGES.rst
src/ZODB/FileStorage/fspack.py
src/ZODB/FileStorage/tests.py

This incorporates the requested updates from #22.

Update issue #22

---

setup.py

Use PEP-426 environment markers

---

CHANGES.rst
doc/HISTORY.rst
src/ZODB/Connection.py
src/ZODB/tests/testMVCCMappingStorage.py

Do3cc fix for45 master

---

src/ZODB/historical_connections.txt

The PR depended on system time being UTC.

Fixed test failure introduced in pull-request 51

---

src/ZODB/tests/HistoryStorage.py
src/ZODB/tests/synchronizers.txt
src/ZODB/tests/testFileStorage.py

This should fix #60 (I have no Windows box to test).

Fix winbot failures

---

setup.py
src/ZODB/Connection.py
src/ZODB/DB.py
src/ZODB/historical_connections.txt
src/ZODB/interfaces.py
src/ZODB/mvccadapter.py
src/ZODB/tests/blob_connection.txt
src/ZODB/tests/testConnection.py
src/ZODB/tests/testDB.py
src/ZODB/tests/testblob.py
src/ZODB/tests/testmvcc.py

That's applied to storages other than RelStorage.
See: https://groups.google.com/forum/#!topic/zodb/QJYmvF0eUUM

Abstract ZODB's MVCC implementation into a storage adapter.

---

src/ZODB/BaseStorage.py
src/ZODB/FileStorage/tests.py
src/ZODB/blob.py
src/ZODB/scripts/fsrefs.py
src/ZODB/scripts/netspace.py
src/ZODB/scripts/space.py
src/ZODB/tests/BasicStorage.py
src/ZODB/tests/ConflictResolution.py
src/ZODB/tests/Corruption.py
src/ZODB/tests/IteratorStorage.py
src/ZODB/tests/MTStorage.py
src/ZODB/tests/PackableStorage.py
src/ZODB/tests/PersistentStorage.py
src/ZODB/tests/ReadOnlyStorage.py
src/ZODB/tests/RecoveryStorage.py
src/ZODB/tests/RevisionStorage.py
src/ZODB/tests/TransactionalUndoStorage.py
src/ZODB/tests/testDemoStorage.py
src/ZODB/tests/testFileStorage.py
src/ZODB/tests/testblob.py

This is a *very* mechanical PR to get rid of storage (not count IMVCCStorage) load calls.

Stop calling load

---

src/ZODB/Connection.py
src/ZODB/DB.py
src/ZODB/DemoStorage.py
src/ZODB/FileStorage/FileStorage.py
src/ZODB/FileStorage/interfaces.py
src/ZODB/MappingStorage.py
src/ZODB/component.xml
src/ZODB/config.py
src/ZODB/interfaces.py
src/ZODB/valuedoc.py

Lot's of doc string changes and ZConfig updates to support generating reference documentation for zodb.org.
I've made a snapshot here: to facilitate review.
It's tempting to move the zodb docs into this repo to make reviewing changes easier.

Reference docs

---

doc/reference/storages.rst
doc/reference/zodb.rst

In this PR, there's still a missing commit to add a entry for NEO. BTW, shall we sort alphabetically :)

Noteworthy non-included storages: split base storages from others, NEO

---

doc/guide/writing-persistent-objects.rst

Here's a first draft. Comments welcome!

Add a section on the pitfalls of __eq__/__hash__. Fixes #106.

---

CHANGES.rst
src/ZODB/DB.py
src/ZODB/tests/BasicStorage.py
src/ZODB/tests/PackableStorage.py
src/ZODB/tests/RecoveryStorage.py
src/ZODB/tests/RevisionStorage.py
src/ZODB/tests/StorageTestBase.py
src/ZODB/tests/TransactionalUndoStorage.py
src/ZODB/tests/dangle.py
src/ZODB/tests/testConnection.py
src/ZODB/tests/testFileStorage.py
src/ZODB/tests/testMVCCMappingStorage.py
src/ZODB/tests/testZODB.py
src/ZODB/tests/test_fsdump.py
src/ZODB/tests/testfsoids.py

Fixed to work with transaction 2.0.3.

---

src/ZODB/DB.py
src/ZODB/tests/multidb.txt
src/ZODB/tests/testDB.py

otherwise persistent object seem to hang around
noticed by our tests

Clean DB properties on close

---

doc/index.rst

Especially with regard to write capacity and search.
This hasn't been updated in a while and I feel that it is out of date.
I feel that this could use more work, but I'm anxious to do an
incremental improvement given the screencast I just released. :)

Update the front page to be a little less negative.

---

CHANGES.rst

Fix a spelling error

---

CHANGES.rst
setup.py
src/ZODB/tests/util.py

Fix tests with, and depend on, persistent 4.4.

---

doc/index.rst

ZODB Doc Typo

---

doc/articles/ZODB2.rst

Spellcheck error in ZODB2.rst

---

src/ZODB/scripts/repozo.py
src/ZODB/scripts/tests/test_repozo.py

repozo -B with missing -f should show a clear error message

---

.coveragerc
doc/reference/storages.rst
src/ZODB/scripts/repozo.py
src/ZODB/tests/testThreadedShutdown.py

Fix ResourceWarnings seen during testing, and a testrunner orphaned thread warning

---

.travis.yml
CHANGES.rst
appveyor.yml
setup.py
tox.ini

modified:   .travis.yml
modified:   CHANGES.rst
modified:   setup.py
modified:   tox.ini

Add support for Python 3.8.

---

src/ZODB/interfaces.py

Fix simple typo: whos -> whose

---

CHANGES.rst
doc/guide/writing-persistent-objects.rst

I took the statements and insight from #292 and enhanced the documentation.

fix #292 improve volatile attribute documentation

---

CHANGES.rst
src/ZODB/FileStorage/tests.py
src/ZODB/mvccadapter.py
src/ZODB/tests/testConnection.py
src/ZODB/tests/testmvcc.py

mvccadapter: fix race with invalidations when starting a new transaction

---

doc/index.rst

The project is not really active, but perhaps it lacks visibility?

Added newtdb link

---

buildout.cfg
doc/requirements.txt

~~Else it is failing as:~~
~~...~~
~~(see e.g. https://travis-ci.com/github/zopefoundation/ZODB/jobs/499760337)~~
Fix buildout-related CI issues.
Suggested by @d-maurer.

buildout: Fix CI

---

.github/workflows/tests.yml
.meta.toml
setup.cfg
tox.ini

... and turn off `with-future-python` for the moment, it suffers from the same `cffi`-related issues Michael has seen in other packages.

Update to the latest meta/config template
